name: IntroQCryptoBook
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - python=3.11.0
  - numpy=1.24.3
  - matplotlib=3.7.1
  - webio-jupyter-extension=0.1.0
  - notebook=6.5.2
