name: IntroQCryptoBook
channels:
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - python=3.11.*
  - numpy=1.24.*
  - matplotlib=3.7.*
  - webio-jupyter-extension=0.1.*
  - notebook=6.5.*
